// Shreyu_v1.0.2/Admin/angular/src/app/pages/apps/tasks/tasklist/tasklist.component.ts
import { Component, OnInit } from '@angular/core';

import { tasks } from './data';

import { Tasks } from './tasklist.model';

@Component({
  selector: 'app-tasklist',
  templateUrl: './tasklist.component.html',
  styleUrls: ['./tasklist.component.scss']
})

/**
 * Task-list component - handling task-list with sidebar and content
 */
export class TasklistComponent implements OnInit {

  // bread crumb items
  breadCrumbItems: Array<{}>;

  todayTask: boolean;
  upcomingTasks: boolean;
  otherTasks: boolean;

  todayTasks: Tasks[];
  upcomingTask: Tasks[];
  otherTask: Tasks[];

  constructor() { }

  ngOnInit() {
    // tslint:disable-next-line: max-line-length
    this.breadCrumbItems = [{ label: 'Shreyu', path: '/' }, { label: 'Apps', path: '/' }, { label: 'Tasks', path: '/' }, { label: 'List', active: true }];

    this.todayTask = false;
    this.upcomingTasks = false;
    this.otherTasks = false;

    /**
     * Fetches the task data
     */
    this._fetchData();
  }

  /**
   * Fetches and filter the data
   */
  private _fetchData() {
    this.todayTasks = tasks.filter(t => t.id === 'today');
    this.upcomingTask = tasks.filter(t => t.id === 'upcoming');
    this.otherTask = tasks.filter(t => t.id === 'other');
  }
}

<div class="container-fluid">
  <app-page-title title="Tasks List" [breadcrumbItems]="breadCrumbItems"></app-page-title>
  <!-- tasks panel -->
  <div class="row">
    <div class="col-xl-8">
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-body">
              <!-- cta -->
              <div class="row">
                <div class="col-sm-3">
                  <a href="javascript: void(0);" class="btn btn-primary"><i class='uil uil-plus mr-1'></i>Add New</a>
                </div>
                <div class="col-sm-9">
                  <div class="float-sm-right mt-3 mt-sm-0">

                    <div class="task-search d-inline-block mb-3 mb-sm-0 mr-sm-3">
                      <form>
                        <div class="input-group">
                          <input type="text" class="form-control search-input" placeholder="Search..." />
                          <span class="uil uil-search icon-search"></span>
                          <div class="input-group-append">
                            <button class="btn btn-soft-primary" type="button">
                              <i class='uil uil-file-search-alt'></i>
                            </button>
                          </div>
                        </div>
                      </form>
                    </div>
                    <div class="dropdown d-inline-block" ngbDropdown>
                      <button class="btn btn-secondary dropdown-toggle" type="button" ngbDropdownToggle>
                        <i class='uil uil-sort-amount-down'></i>
                      </button>
                      <div class="dropdown-menu dropdown-menu-right" ngbDropdownMenu>
                        <a class="dropdown-item" href="javascript: void(0);">Due Date</a>
                        <a class="dropdown-item" href="javascript: void(0);">Added Date</a>
                        <a class="dropdown-item" href="javascript: void(0);">Assignee</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="row mt-4">
                <div class="col">
                  <a class="text-dark" href="javascript: void(0);" (click)="todayTask = !todayTask"
                    aria-controls="todayTasks">
                    <h5 class="mb-0"><i class='font-size-18 mr-1 uil' [ngClass]="{'uil-angle-down': !todayTask, 'uil-angle-right': todayTask}"></i>Today <span
                        class="text-muted font-size-14">(10)</span></h5>
                  </a>
                  <div class="collapse show" id="todayTasks" [ngbCollapse]="todayTask">
                    <div class="card mb-0 shadow-none">
                      <div class="card-body pt-0">
                        <ng-template [ngTemplateOutlet]="todaytask" [ngTemplateOutletContext]="{task:task, i:i}"
                          *ngFor="let task of todayTasks;let i = index;"></ng-template>
                      </div> <!-- end card-body-->
                    </div> <!-- end card -->
                  </div> <!-- end .collapse-->

                  <!-- upcoming tasks -->
                  <div class="mt-4">
                    <a class="text-dark" href="javascript: void(0);" (click)="upcomingTasks = !upcomingTasks"
                      aria-controls="upcomingTasks">
                      <h5 class="mb-0">
                          <i class='font-size-18 mr-1 uil' [ngClass]="{'uil-angle-down': !upcomingTasks, 'uil-angle-right': upcomingTasks}"></i>Upcoming <span
                          class="text-muted font-size-14">(5)</span>
                      </h5>
                    </a>
                    <div class="collapse show" id="upcomingTasks" [ngbCollapse]="upcomingTasks">
                      <div class="card mb-0 shadow-none">
                        <div class="card-body pt-0">
                          <!-- task -->
                          <ng-template [ngTemplateOutlet]="upcomingtask" [ngTemplateOutletContext]="{task:task,i: i}"
                            *ngFor="let task of upcomingTask;let i = index;"></ng-template>
                          <!-- end task -->
                        </div> <!-- end card-body-->
                      </div> <!-- end card -->
                    </div> <!-- end collapse-->
                  </div>
                  <!-- end upcoming tasks -->

                  <!-- start other tasks -->
                  <div class="mt-4 mb-4">
                    <a class="text-dark" href="javascript: void(0);" (click)="otherTasks = !otherTasks"
                      aria-controls="otherTasks">
                      <h5>
                          <i class='font-size-18 mr-1 uil' [ngClass]="{'uil-angle-down': !otherTasks, 'uil-angle-right': otherTasks}"></i>Other <span class="text-muted font-size-14">(5)</span>
                      </h5>
                    </a>
                    <div class="collapse show" id="otherTasks" [ngbCollapse]="otherTasks">
                      <div class="card mb-0 shadow-none">
                        <div class="card-body pt-0">
                          <!-- task -->
                          <ng-template [ngTemplateOutlet]="othertask" [ngTemplateOutletContext]="{task:task, i: i}"
                            *ngFor="let task of otherTask;let i = index;"></ng-template>
                        </div> <!-- end card-body-->
                      </div> <!-- end card -->
                    </div>
                  </div>
                </div>
              </div>

              <div class="row mb-3 mt-5">
                <div class="col-12">
                  <div class="text-center">
                    <a href="javascript:void(0);" class="btn btn-white mb-3">
                      <i data-feather="loader" class="icon-dual icon-xs mr-2"></i>
                      Load more
                    </a>
                  </div>
                </div> <!-- end col-->
              </div>
              <!-- end row -->
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- task details -->
    <div class="col-xl-4">
      <div class="card">
        <div class="card-body">
          <div class="row pb-3 border-bottom">
            <div class="col">
              <div class="dropdown float-right" ngbDropdown>
                <a href="javascript: void(0);" class="dropdown-toggle arrow-none text-muted" ngbDropdownToggle>
                  <i class='uil uil-ellipsis-h'></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" ngbDropdownMenu>
                  <!-- item-->
                  <a href="javascript:void(0);" class="dropdown-item">
                    <i class='uil uil-file-upload mr-1'></i>Attachment
                  </a>
                  <!-- item-->
                  <a href="javascript:void(0);" class="dropdown-item">
                    <i class='uil uil-edit mr-1'></i>Edit
                  </a>
                  <!-- item-->
                  <a href="javascript:void(0);" class="dropdown-item">
                    <i class='uil uil-file-copy-alt mr-1'></i>Mark as Duplicate
                  </a>
                  <div class="dropdown-divider"></div>
                  <!-- item-->
                  <a href="javascript:void(0);" class="dropdown-item text-danger">
                    <i class='uil uil-trash-alt mr-1'></i>Delete
                  </a>
                </div> <!-- end dropdown menu-->
              </div> <!-- end dropdown-->

              <div class="custom-control custom-checkbox float-left">
                <input type="checkbox" class="custom-control-input" id="completedCheck">
                <label class="custom-control-label" for="completedCheck">
                  Mark as completed
                </label>
              </div> <!-- end custom-checkbox-->
            </div>
          </div>

          <div class="row">
            <div class="col">
              <h4 class="mt-3">Draft the new contract document for sales team</h4>

              <div class="row">
                <div class="col-6">
                  <!-- assignee -->
                  <p class="mt-2 mb-1 text-muted">Assigned To</p>
                  <div class="media">
                    <img src="assets/images/users/avatar-9.jpg" alt="Arya S" class="rounded-circle mr-2" height="24" />
                    <div class="media-body">
                      <h5 class="mt-1 font-size-14">
                        Arya Stark
                      </h5>
                    </div>
                  </div>
                  <!-- end assignee -->
                </div> <!-- end col -->

                <div class="col-6">
                  <!-- start due date -->
                  <p class="mt-2 mb-1 text-muted">Due Date</p>
                  <div class="media">
                    <i class='uil uil-schedule font-18 text-success mr-1'></i>
                    <div class="media-body">
                      <h5 class="mt-1 font-size-14">
                        Today 10am
                      </h5>
                    </div>
                  </div>
                  <!-- end due date -->
                </div> <!-- end col -->
              </div> <!-- end row -->

              <!-- task description -->
              <div class="row mt-3">
                <div class="col">
                  <div id="taskDesk">
                    <p>This is a task description with markup support</p>
                    <ul>
                      <li>Select a text to reveal the toolbar.</li>
                      <li>Edit rich document on-the-fly, so elastic!</li>
                    </ul>
                    <p>End of air-mode area</p>
                  </div>
                </div> <!-- end col -->
              </div>
              <!-- end task description -->

              <!-- start sub tasks/checklists -->
              <h5 class="mt-4 mb-2 font-size-16">Checklists/Sub-tasks</h5>
              <div class="custom-control custom-checkbox mt-1">
                <input type="checkbox" class="custom-control-input" id="checklist1">
                <label class="custom-control-label strikethrough" for="checklist1">
                  Find out the old contract documents
                </label>
              </div>

              <div class="custom-control custom-checkbox mt-1">
                <input type="checkbox" class="custom-control-input" id="checklist2">
                <label class="custom-control-label strikethrough" for="checklist2">
                  Organize meeting sales associates to understand need in detail
                </label>
              </div>

              <div class="custom-control custom-checkbox mt-1">
                <input type="checkbox" class="custom-control-input" id="checklist3">
                <label class="custom-control-label strikethrough" for="checklist3">
                  Make sure to cover every small details
                </label>
              </div>
              <!-- end sub tasks/checklists -->

              <!-- start attachments -->
              <h5 class="mt-4 mb-2 font-size-16">Attachments</h5>
              <div class="card mb-2 shadow-none border">
                <div class="p-1 px-2">
                  <div class="row align-items-center">
                    <div class="col-auto">
                      <img src="assets/images/projects/project-1.jpg" class="avatar-sm rounded" alt="file-image">
                    </div>
                    <div class="col pl-0">
                      <a href="javascript:void(0);" class="text-muted font-weight-bold">sales-assets.zip</a>
                      <p class="mb-0">2.3 MB</p>
                    </div>
                    <div class="col-auto">
                      <!-- Button -->
                      <a href="javascript:void(0);" data-toggle="tooltip" data-placement="bottom" title="Download"
                        class="btn btn-link text-muted btn-lg p-0">
                        <i class='uil uil-cloud-download font-size-14'></i>
                      </a>
                      <a href="javascript:void(0);" data-toggle="tooltip" data-placement="bottom" title="Delete"
                        class="btn btn-link text-danger btn-lg p-0">
                        <i class='uil uil-multiply font-size-14'></i>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mb-2 shadow-none border">
                <div class="p-1 px-2">
                  <div class="row align-items-center">
                    <div class="col-auto">
                      <img src="assets/images/projects/project-2.jpg" class="avatar-sm rounded" alt="file-image">
                    </div>
                    <div class="col pl-0">
                      <a href="javascript:void(0);" class="text-muted font-weight-bold">new-contarcts.docx</a>
                      <p class="mb-0">1.25 MB</p>
                    </div>
                    <div class="col-auto">
                      <!-- Button -->
                      <a href="javascript:void(0);" data-toggle="tooltip" data-placement="bottom" title="Download"
                        class="btn btn-link text-muted btn-lg p-0">
                        <i class='uil uil-cloud-download font-size-14'></i>
                      </a>
                      <a href="javascript:void(0);" data-toggle="tooltip" data-placement="bottom" title="Delete"
                        class="btn btn-link text-danger btn-lg p-0">
                        <i class='uil uil-multiply font-size-14'></i>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <!-- end attachments -->

              <!-- comments -->
              <div class="row mt-3">
                <div class="col">
                  <h5 class="mb-2 font-size-16">Comments</h5>

                  <div class="media mt-3 p-1">
                    <img src="assets/images/users/avatar-9.jpg" class="mr-2 rounded-circle" height="36"
                      alt="Arya Stark" />
                    <div class="media-body">
                      <h5 class="mt-0 mb-0 font-size-14">
                        <span class="float-right text-muted font-size-12">4:30am</span>
                        Arya Stark
                      </h5>
                      <p class="mt-1 mb-0 text-muted">
                        Should I review the last 3 years legal documents as
                        well?
                      </p>
                    </div>
                  </div> <!-- end comment -->

                  <hr />

                  <div class="media mt-2 p-1">
                    <img src="assets/images/users/avatar-5.jpg" class="mr-2 rounded-circle" height="36"
                      alt="Dominc B" />
                    <div class="media-body">
                      <h5 class="mt-0 mb-0 font-size-14">
                        <span class="float-right text-muted font-size-12">3:30am</span>
                        Gary Somya
                      </h5>
                      <p class="mt-1 mb-0 text-muted">
                        @Arya FYI..I have created some general guidelines last
                        year.
                      </p>
                    </div>
                  </div> <!-- end comment-->

                  <hr />

                </div> <!-- end col -->
              </div> <!-- end row -->

              <div class="row mt-2">
                <div class="col">
                  <div class="border rounded">
                    <form action="#" class="comment-area-box">
                      <textarea rows="3" class="form-control border-0 resize-none"
                        placeholder="Your comment..."></textarea>
                      <div class="p-2 bg-light">
                        <div class="float-right">
                          <button type="submit" class="btn btn-sm btn-success"><i
                              class='uil uil-message mr-1'></i>Submit</button>
                        </div>
                        <div>
                          <a href="javascript: void(0);" class="btn btn-sm px-1 btn-light"><i
                              class='uil uil-cloud-upload'></i></a>
                          <a href="javascript: void(0);" class="btn btn-sm px-1 btn-light"><i
                              class='uil uil-at'></i></a>
                        </div>
                      </div>
                    </form>
                  </div> <!-- end .border-->
                </div> <!-- end col-->
              </div> <!-- end row-->
              <!-- end comments -->
            </div> <!-- end col -->
          </div> <!-- end row-->
        </div> <!-- end card-body -->
      </div> <!-- end card-->
    </div> <!-- end col -->
  </div>
</div>

<!-- today task data -->
<ng-template #todaytask let-task='task' let-i='i'>
  <div class="row justify-content-sm-between border-bottom mt-2 pt-2">
    <div class="col-lg-6 mb-2 mb-lg-0">
      <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="task-today-{{i}}">
        <label class="custom-control-label" for="task-today-{{i}}">
          {{ task.name }}
        </label>
      </div> <!-- end checkbox -->
    </div> <!-- end col -->
    <div class="col-lg-6">
      <div class="d-sm-flex justify-content-between">
        <div>
          <img src="{{ task.user }}" alt="image" class="avatar-xs rounded-circle" />
        </div>
        <div class="mt-3 mt-sm-0">
          <ul class="list-inline font-13 text-sm-right">
            <li class="list-inline-item pr-1">
              <i class='uil uil-schedule font-16 mr-1'></i>
              {{task.time}}
            </li>
            <li class="list-inline-item pr-1">
              <i class='uil uil-align-alt font-16 mr-1'></i>
              {{task.task}}
            </li>
            <li class="list-inline-item pr-2">
              <i class='uil uil-comment-message font-16 mr-1'></i>
              {{ task.message }}
            </li>
            <li class="list-inline-item">
              <span class="badge p-1" [ngClass]="{
                                                              'badge-soft-danger': task.status === 'High',
                                                              'badge-soft-info': task.status === 'Medium',
                                                              'badge-soft-success': task.status === 'Low'
                                                          }">{{ task.status }}</span>
            </li>
          </ul>
        </div>
      </div> <!-- end .d-flex-->
    </div> <!-- end col -->
  </div>
</ng-template>

<!-- Upcoming task data -->
<ng-template #upcomingtask let-task='task' let-i='i'>
  <div class="row justify-content-sm-between border-bottom mt-2 pt-2">
    <div class="col-lg-6 mb-2 mb-lg-0">
      <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="task-upcoming-{{i}}">
        <label class="custom-control-label" for="task-upcoming-{{i}}">
          {{ task.name }}
        </label>
      </div> <!-- end checkbox -->
    </div> <!-- end col -->
    <div class="col-lg-6">
      <div class="d-sm-flex justify-content-between">
        <div>
          <img src="{{ task.user }}" alt="image" class="avatar-xs rounded-circle" />
        </div>
        <div class="mt-3 mt-sm-0">
          <ul class="list-inline font-13 text-sm-right">
            <li class="list-inline-item pr-1">
              <i class='uil uil-schedule font-16 mr-1'></i>
              {{task.time}}
            </li>
            <li class="list-inline-item pr-1">
              <i class='uil uil-align-alt font-16 mr-1'></i>
              {{task.task}}
            </li>
            <li class="list-inline-item pr-2">
              <i class='uil uil-comment-message font-16 mr-1'></i>
              {{ task.message }}
            </li>
            <li class="list-inline-item">
              <span class="badge p-1" [ngClass]="{
                                                  'badge-soft-danger': task.status === 'High',
                                                  'badge-soft-info': task.status === 'Medium',
                                                  'badge-soft-success': task.status === 'Low'
                                              }">{{ task.status }}</span>
            </li>
          </ul>
        </div>
      </div> <!-- end .d-flex-->
    </div> <!-- end col -->
  </div>
</ng-template>

<!-- Other task data -->
<ng-template #othertask let-task='task' let-i='i'>
  <div class="row justify-content-sm-between border-bottom mt-2 pt-2">
    <div class="col-lg-6 mb-2 mb-lg-0">
      <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="task-other-{{i}}">
        <label class="custom-control-label" for="task-other-{{i}}">
          {{ task.name }}
        </label>
      </div> <!-- end checkbox -->
    </div> <!-- end col -->
    <div class="col-lg-6">
      <div class="d-sm-flex justify-content-between">
        <div>
          <img src="{{ task.user }}" alt="image" class="avatar-xs rounded-circle" />
        </div>
        <div class="mt-3 mt-sm-0">
          <ul class="list-inline font-13 text-sm-right">
            <li class="list-inline-item pr-1">
              <i class='uil uil-schedule font-16 mr-1'></i>
              {{task.time}}
            </li>
            <li class="list-inline-item pr-1">
              <i class='uil uil-align-alt font-16 mr-1'></i>
              {{task.task}}
            </li>
            <li class="list-inline-item pr-2">
              <i class='uil uil-comment-message font-16 mr-1'></i>
              {{ task.message }}
            </li>
            <li class="list-inline-item">
              <span class="badge p-1" [ngClass]="{
                                                                  'badge-soft-danger': task.status === 'High',
                                                                  'badge-soft-info': task.status === 'Medium',
                                                                  'badge-soft-success': task.status === 'Low'
                                                              }">{{ task.status }}</span>
            </li>
          </ul>
        </div>
      </div> <!-- end .d-flex-->
    </div> <!-- end col -->
  </div>
</ng-template>

// Shreyu_v1.0.2/Admin/vue/src/router/views/pages/apps/tasks/task-list.vue
<script>
import appConfig from '@src/app.config'
import Layout from '@layouts/main'
import PageHeader from '@components/page-header'

import TaskDetail from './task-detail'
import { todayTasks, upcomingTasks, otherTasks } from './data-tasklist'

export default {
  page: {
    title: 'Tasks List',
    meta: [{ name: 'description', content: appConfig.description }],
  },
  components: { Layout, PageHeader, TaskDetail },
  data() {
    return {
      selectedTask: todayTasks[0],
      title: 'Tasks List',
      items: [
        {
          text: 'Shreyu',
          href: '/',
        },
        {
          text: 'Apps',
          href: '/',
        },
        {
          text: 'Tasks',
          href: '/',
        },
        {
          text: 'List',
          active: true,
        },
      ],
      todayTasks: [...todayTasks],
      upcomingTask: [...upcomingTasks],
      otherTask: [...otherTasks],
    }
  },
}
</script>

<template>
  <Layout>
    <PageHeader :title="title" :items="items" />

    <div class="row">
      <div class="col-xl-8">
        <div class="row">
          <div class="col">
            <div class="card">
              <div class="card-body">
                <!-- cta -->
                <div class="row">
                  <div class="col-sm-3">
                    <a href="javascript: void(0);" class="btn btn-primary">
                      <i class="uil uil-plus mr-1"></i>Add New
                    </a>
                  </div>
                  <div class="col-sm-9">
                    <div class="float-sm-right mt-3 mt-sm-0">
                      <div
                        class="task-search d-inline-block mb-3 mb-sm-0 mr-sm-3"
                      >
                        <form>
                          <div class="input-group">
                            <input
                              type="text"
                              class="form-control search-input"
                              placeholder="Search..."
                            />
                            <span class="uil uil-search icon-search"></span>
                            <div class="input-group-append">
                              <button
                                class="btn btn-soft-primary"
                                type="button"
                              >
                                <i class="uil uil-file-search-alt"></i>
                              </button>
                            </div>
                          </div>
                        </form>
                      </div>

                      <b-dropdown id="sort-act" class="d-inline-block" right>
                        <template v-slot:button-content>
                          <i class="uil uil-sort-amount-down"></i>
                        </template>
                        <b-dropdown-item>Due Date</b-dropdown-item>
                        <b-dropdown-item>Added Date</b-dropdown-item>
                        <b-dropdown-item>Assignee</b-dropdown-item>
                      </b-dropdown>
                    </div>
                  </div>
                </div>

                <div class="row mt-4">
                  <div class="col">
                    <a
                      v-b-toggle.todayTasks
                      class="text-dark"
                      href="javascript: void(0);"
                      aria-controls="todayTasks"
                    >
                      <h5 class="mb-0">
                        <i class="uil uil-angle-down font-size-18"></i>Today
                        <span class="text-muted font-size-14"
                          >({{ todayTasks.length }})</span
                        >
                      </h5>
                    </a>
                    <b-collapse id="todayTasks" visible>
                      <div class="card mb-0 shadow-none">
                        <div class="card-body pt-0">
                          <div
                            v-for="(task, index) of todayTasks"
                            :key="index"
                            class="row justify-content-sm-between border-bottom mt-2 pt-2"
                          >
                            <div class="col-lg-6 mb-2 mb-lg-0">
                              <div class="custom-control custom-checkbox">
                                <input
                                  :id="`task-${index}`"
                                  type="checkbox"
                                  class="custom-control-input"
                                />
                                <label
                                  class="custom-control-label"
                                  :for="`task-${index}`"
                                  >{{ task.title }}</label
                                >
                              </div>
                              <!-- end checkbox -->
                            </div>
                            <!-- end col -->
                            <div class="col-lg-6">
                              <div class="d-sm-flex justify-content-between">
                                <div>
                                  <img
                                    v-b-tooltip.hover
                                    :title="`Assigned to ${task.assigned_to}`"
                                    :src="`${task.assignee_avatar}`"
                                    alt="image"
                                    class="avatar-xs rounded-circle"
                                  />
                                </div>
                                <div class="mt-3 mt-sm-0">
                                  <ul class="list-inline font-13 text-sm-right">
                                    <li class="list-inline-item pr-1">
                                      <i
                                        class="uil uil-schedule font-16 mr-1"
                                      ></i>
                                      {{ task.due_date }}
                                    </li>
                                    <li class="list-inline-item pr-1">
                                      <i
                                        class="uil uil-align-alt font-16 mr-1"
                                      ></i>
                                      {{ task.checklists.length }}
                                    </li>
                                    <li class="list-inline-item pr-2">
                                      <i
                                        class="uil uil-comment-message font-16 mr-1"
                                      ></i>
                                      {{ task.comments.length }}
                                    </li>
                                    <li class="list-inline-item">
                                      <span
                                        class="badge p-1"
                                        :class="{
                                          'badge-soft-danger':
                                            `${task.priority}` === 'High',
                                          'badge-soft-info':
                                            `${task.priority}` === 'Medium',
                                          'badge-soft-success':
                                            `${task.priority}` === 'Low',
                                        }"
                                        >{{ task.priority }}</span
                                      >
                                    </li>
                                  </ul>
                                </div>
                              </div>
                              <!-- end .d-flex-->
                            </div>
                            <!-- end col -->
                          </div>
                          <!-- end card-body-->
                        </div>
                        <!-- end card -->
                      </div>
                      <!-- end .collapse-->

                      <!-- upcoming tasks -->
                    </b-collapse>

                    <div class="mt-4">
                      <a
                        v-b-toggle.upcomingTask
                        class="text-dark"
                        href="javascript: void(0);"
                        aria-controls="upcomingTask"
                      >
                        <h5 class="mb-0">
                          <i class="uil uil-angle-down font-size-18"></i
                          >Upcoming
                          <span class="text-muted font-size-14"
                            >({{ upcomingTask.length }})</span
                          >
                        </h5>
                      </a>
                      <b-collapse id="upcomingTask" visible>
                        <div class="card mb-0 shadow-none">
                          <div class="card-body pt-0">
                            <div
                              v-for="(task, index) of upcomingTask"
                              :key="index"
                              class="row justify-content-sm-between border-bottom mt-2 pt-2"
                            >
                              <div class="col-lg-6 mb-2 mb-lg-0">
                                <div class="custom-control custom-checkbox">
                                  <input
                                    :id="`task-upcoming-${index}`"
                                    type="checkbox"
                                    class="custom-control-input"
                                  />
                                  <label
                                    class="custom-control-label"
                                    :for="`task-upcoming-${index}`"
                                    >{{ task.title }}</label
                                  >
                                </div>
                                <!-- end checkbox -->
                              </div>
                              <!-- end col -->
                              <div class="col-lg-6">
                                <div class="d-sm-flex justify-content-between">
                                  <div>
                                    <img
                                      v-b-tooltip.hover
                                      :title="`Assigned to ${task.assigned_to}`"
                                      :src="`${task.assignee_avatar}`"
                                      alt="image"
                                      class="avatar-xs rounded-circle"
                                    />
                                  </div>
                                  <div class="mt-3 mt-sm-0">
                                    <ul
                                      class="list-inline font-13 text-sm-right"
                                    >
                                      <li class="list-inline-item pr-1">
                                        <i
                                          class="uil uil-schedule font-16 mr-1"
                                        ></i>
                                        {{ task.due_date }}
                                      </li>
                                      <li class="list-inline-item pr-1">
                                        <i
                                          class="uil uil-align-alt font-16 mr-1"
                                        ></i>
                                        {{ task.checklists.length }}
                                      </li>
                                      <li class="list-inline-item pr-2">
                                        <i
                                          class="uil uil-comment-message font-16 mr-1"
                                        ></i>
                                        {{ task.comments.length }}
                                      </li>
                                      <li class="list-inline-item">
                                        <span
                                          class="badge p-1"
                                          :class="{
                                            'badge-soft-danger':
                                              `${task.priority}` === 'High',
                                            'badge-soft-info':
                                              `${task.priority}` === 'Medium',
                                            'badge-soft-success':
                                              `${task.priority}` === 'Low',
                                          }"
                                          >{{ task.priority }}</span
                                        >
                                      </li>
                                    </ul>
                                  </div>
                                </div>
                                <!-- end .d-flex-->
                              </div>
                              <!-- end col -->
                            </div>
                            <!-- end card-body-->
                          </div>
                          <!-- end card -->
                        </div>
                        <!-- end .collapse-->

                        <!-- upcoming tasks -->
                      </b-collapse>
                    </div>

                    <div class="mt-4">
                      <a
                        v-b-toggle.otherTask
                        class="text-dark"
                        href="javascript: void(0);"
                        aria-controls="otherTask"
                      >
                        <h5 class="mb-0">
                          <i class="uil uil-angle-down font-size-18"></i>Other
                          <span class="text-muted font-size-14"
                            >({{ otherTask.length }})</span
                          >
                        </h5>
                      </a>
                      <b-collapse id="otherTask" visible>
                        <div class="card mb-0 shadow-none">
                          <div class="card-body pt-0">
                            <div
                              v-for="(task, index) of otherTask"
                              :key="index"
                              class="row justify-content-sm-between border-bottom mt-2 pt-2"
                            >
                              <div class="col-lg-6 mb-2 mb-lg-0">
                                <div class="custom-control custom-checkbox">
                                  <input
                                    :id="`task-other-${index}`"
                                    type="checkbox"
                                    class="custom-control-input"
                                  />
                                  <label
                                    class="custom-control-label"
                                    :for="`task-other-${index}`"
                                    >{{ task.title }}</label
                                  >
                                </div>
                                <!-- end checkbox -->
                              </div>
                              <!-- end col -->
                              <div class="col-lg-6">
                                <div class="d-sm-flex justify-content-between">
                                  <div>
                                    <img
                                      v-b-tooltip.hover
                                      :title="`Assigned to ${task.assigned_to}`"
                                      :src="`${task.assignee_avatar}`"
                                      alt="image"
                                      class="avatar-xs rounded-circle"
                                    />
                                  </div>
                                  <div class="mt-3 mt-sm-0">
                                    <ul
                                      class="list-inline font-13 text-sm-right"
                                    >
                                      <li class="list-inline-item pr-1">
                                        <i
                                          class="uil uil-schedule font-16 mr-1"
                                        ></i>
                                        {{ task.due_date }}
                                      </li>
                                      <li class="list-inline-item pr-1">
                                        <i
                                          class="uil uil-align-alt font-16 mr-1"
                                        ></i>
                                        {{ task.checklists.length }}
                                      </li>
                                      <li class="list-inline-item pr-2">
                                        <i
                                          class="uil uil-comment-message font-16 mr-1"
                                        ></i>
                                        {{ task.comments.length }}
                                      </li>
                                      <li class="list-inline-item">
                                        <span
                                          class="badge p-1"
                                          :class="{
                                            'badge-soft-danger':
                                              `${task.priority}` === 'High',
                                            'badge-soft-info':
                                              `${task.priority}` === 'Medium',
                                            'badge-soft-success':
                                              `${task.priority}` === 'Low',
                                          }"
                                          >{{ task.priority }}</span
                                        >
                                      </li>
                                    </ul>
                                  </div>
                                </div>
                                <!-- end .d-flex-->
                              </div>
                              <!-- end col -->
                            </div>
                            <!-- end card-body-->
                          </div>
                          <!-- end card -->
                        </div>
                        <!-- end .collapse-->

                        <!-- upcoming tasks -->
                      </b-collapse>
                    </div>
                  </div>
                  <!-- end row -->
                </div>
                <div class="row mb-3 mt-5">
                  <div class="col-12">
                    <div class="text-center">
                      <a href="javascript:void(0);" class="btn btn-white mb-3">
                        <feather
                          type="loader"
                          class="icon-dual icon-xs mr-2 align-middle"
                        ></feather
                        >Load more
                      </a>
                    </div>
                  </div>
                  <!-- end col-->
                </div>
                <!-- end row -->
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- task details -->
      <div class="col-xl-4">
        <TaskDetail :task="selectedTask" />
      </div>
      <!-- end col -->
    </div>
  </Layout>
</template>
