// react/src/components/Footer.js
import React, { Component } from 'react';

/**
 * Renders the Footer
 */
class Footer extends Component {

    render() {
        return (
            <footer className="footer">
                <div className="container-fluid">
                    <div className="row">
                        <div className="col-12">
                            2021 &copy; Nemea LLC. All Rights Reserved. Crafted with <i className='uil uil-heart text-danger font-size-12'></i> by
                            <a href="https://nemea.xyz" target="_blank" rel="noopener noreferrer" className="ml-1">Nemea LLC</a>
                        </div>
                    </div>
                </div>
            </footer>
        )
    }
}

export default Footer;

// Shreyu_v1.0.2/Admin/vue/src/components/footer.vue
<template>
  <!-- Footer Start -->
  <footer class="footer">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          2019 &copy; Shreyu. All Rights Reserved. Crafted with
          <i class="uil uil-heart text-danger font-size-12"></i> by
          <a href="https://coderthemes.com" target="_blank">Coderthemes</a>
        </div>
      </div>
    </div>
  </footer>
  <!-- end Footer -->
</template>
