// react/src/components/LeftSidebar.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import { connect } from 'react-redux';

import { isMobileOnly } from "react-device-detect";
import PerfectScrollbar from 'react-perfect-scrollbar';
import 'react-perfect-scrollbar/dist/css/styles.css';

import { UncontrolledDropdown, DropdownMenu, DropdownToggle, DropdownItem } from 'reactstrap';
import * as FeatherIcon from 'react-feather';

import AppMenu from './AppMenu';
import profilePic from '../assets/images/users/avatar-7.jpg';


/**
 * User Widget
 */
const UserProfile = () => {
    return <React.Fragment>
        <div className="media user-profile mt-2 mb-2">
            <img src={profilePic} className="avatar-sm rounded-circle mr-2" alt="Shreyu" />
            <img src={profilePic} className="avatar-xs rounded-circle mr-2" alt="Shreyu" />

            <div className="media-body">
                <h6 className="pro-user-name mt-0 mb-0">Alexander Templeton</h6>
                <span className="pro-user-desc">Administrator</span>
            </div>

            <UncontrolledDropdown className="align-self-center profile-dropdown-menu">
                <DropdownToggle
                    data-toggle="dropdown"
                    tag="button"
                    className="btn btn-link p-0 dropdown-toggle mr-0">
                    <FeatherIcon.ChevronDown />
                </DropdownToggle>
                <DropdownMenu right className="topbar-dropdown-menu profile-dropdown-items">
                    <Link to="/" className="dropdown-item notify-item">
                        <FeatherIcon.User className="icon-dual icon-xs mr-2" />
                        <span>My Account</span>
                    </Link>
                    <Link to="/" className="dropdown-item notify-item">
                        <FeatherIcon.Settings className="icon-dual icon-xs mr-2" />
                        <span>Settings</span>
                    </Link>
                    <Link to="/" className="dropdown-item notify-item">
                        <FeatherIcon.HelpCircle className="icon-dual icon-xs mr-2" />
                        <span>Support</span>
                    </Link>
                    <Link to="/" className="dropdown-item notify-item">
                        <FeatherIcon.Lock className="icon-dual icon-xs mr-2" />
                        <span>Lock Screen</span>
                    </Link>
                    <DropdownItem divider />
                    <Link to="/account/logout" className="dropdown-item notify-item">
                        <FeatherIcon.LogOut className="icon-dual icon-xs mr-2" />
                        <span>Logout</span>
                    </Link>
                </DropdownMenu>
            </UncontrolledDropdown>
        </div>
    </React.Fragment>
}


/**
 * Sidenav
 */
const SideNav = () => {
    return <div className="sidebar-content">
        <div id="sidebar-menu">
            <AppMenu />
        </div>
    </div>
}

class LeftSidebar extends Component {
    menuNodeRef;

    constructor(props) {
        super(props);

        this.handleClick = this.handleClick.bind(this);
        this.handleOtherClick = this.handleOtherClick.bind(this);
    }

    /**
     * Bind event
     */
    componentDidMount = () => {
        document.addEventListener('mousedown', this.handleOtherClick, false);
    };

    /**
     * Bind event
     */
    componentWillUnmount = () => {
        document.removeEventListener('mousedown', this.handleOtherClick, false);
    };

    /**
     * Handle the click anywhere in doc
     */
    handleOtherClick = (e) => {
        if (this.menuNodeRef.contains(e.target)) return;
        // else hide the menubar
        if (document.body && isMobileOnly) {
            document.body.classList.remove('sidebar-enable');
        }
    };

    /**
     * Handle click
     * @param {*} e
     * @param {*} item
     */
    handleClick(e) {
        console.log(e);
    }

    render() {
        const isCondensed = this.props.isCondensed || false;

        return (
            <React.Fragment>
                <div className='left-side-menu' ref={node => this.menuNodeRef = node}>
                    <UserProfile />
                    {!isCondensed && <PerfectScrollbar><SideNav /></PerfectScrollbar>}
                    {isCondensed && <SideNav />}
                </div>
            </React.Fragment>
        );
    }
}

export default connect()(LeftSidebar);

// Shreyu_v1.0.2/Admin/angular/src/app/layouts/shared/leftsidebar/leftsidebar.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Router } from '@angular/router';

import { AuthenticationService } from '../../../core/services/auth.service';
import { SIDEBAR_WIDTH_CONDENSED } from '../../layout.model';

@Component({
  selector: 'app-leftsidebar',
  templateUrl: './leftsidebar.component.html',
  styleUrls: ['./leftsidebar.component.scss'],

})
export class LeftsidebarComponent implements OnInit {

  @Input() sidebarType: string;

  constructor(private router: Router, private authenticationService: AuthenticationService) { }

  ngOnInit() {
  }

  /**
   * Is sidebar condensed?
   */
  isSidebarCondensed() {
    return this.sidebarType === SIDEBAR_WIDTH_CONDENSED;
  }

  /**
   * Logout the user
   */
  logout() {
    this.authenticationService.logout();
    this.router.navigate(['/account/login'], { queryParams: { returnUrl: '/' } });
  }
}

<!-- ========== Left Sidebar Start ========== -->
<div class="left-side-menu">
  <div class="media user-profile mt-2 mb-2">
    <img src="assets/images/users/avatar-7.jpg" class="avatar-sm rounded-circle mr-2" alt="Shreyu">
    <img src="assets/images/users/avatar-7.jpg" class="avatar-xs rounded-circle mr-2" alt="Shreyu">

    <div class="media-body">
      <h6 class="pro-user-name mt-0 mb-0">Shreyu N</h6>
      <span class="pro-user-desc">Administrator</span>
    </div>
    <div class="dropdown align-self-center profile-dropdown-menu" ngbDropdown>
      <a class="dropdown-toggle mr-0" ngbDropdownToggle href="javascript: void(0);">
        <i [attr.data-feather]="'chevron-down'" appFeatherIcon></i>
      </a>
      <div class="dropdown-menu profile-dropdown" ngbDropdownMenu>
        <a routerLink="/pages-profile" class="dropdown-item notify-item">
          <i [attr.data-feather]="'user'" class="icon-dual icon-xs mr-2"></i>
          <span>&nbsp;My Account</span>
        </a>

        <a href="javascript:void(0);" class="dropdown-item notify-item">
          <i [attr.data-feather]="'settings'" class="icon-dual icon-xs mr-2"></i>
          <span>&nbsp;Settings</span>
        </a>

        <a href="javascript:void(0);" class="dropdown-item notify-item">
          <i [attr.data-feather]="'help-circle'" class="icon-dual icon-xs mr-2"></i>
          <span>&nbsp;Support</span>
        </a>

        <a href="javascript: void(0);" class="dropdown-item notify-item">
          <i [attr.data-feather]="'lock'" class="icon-dual icon-xs mr-2"></i>
          <span>&nbsp;Lock Screen</span>
        </a>

        <div class="dropdown-divider"></div>

        <a href="javascript:void(0);" class="dropdown-item notify-item" (click)="logout()">
          <i [attr.data-feather]="'log-out'" class="icon-dual icon-xs mr-2"></i>
          <span>&nbsp;Logout</span>
        </a>
      </div>
    </div>
  </div>


  <div class="sidebar-content">
    <!--- Sidemenu -->
    <div class="h-100" appSlimScroll *ngIf="!isSidebarCondensed()">
      <app-menu id="sidebar-menu"></app-menu>
    </div>

    <div *ngIf="isSidebarCondensed()">
      <app-menu id="sidebar-menu"></app-menu>
    </div>

    <!-- End Sidebar -->
    <div class="clearfix"></div>
  </div>
  <!-- Sidebar -left -->
</div>
<!-- Left Sidebar End -->
